### ISSUE TITLE
GitHub UX Can be Wonky

### ISSUE THREAD

**Issue by Lawhornmatt** [NateDogg97/Group4LOC#2]
HOWDY HOWDY HOWDY HOWDY HOWDY HOWDY HOWDY HOWDY HOWDY HOWDY HOWDY HOWDY HOWDY HOWDY HOWDY HOWDY HOWDY HOWDY HOWDY HOWDY HOWDY HOWDY HOWDY HOWDY HOWDY HOWDY HOWDY HOWDY HOWDY HOWDY HOWDY HOWDY HOWDY HOWDY HOWDY HOWDY HOWDY HOWDY

**Comment by NateDogg97** [comment]
Howdy

**Comment by Lawhornmatt** [comment]
If you make your issue in the already-linked-Repo, then you still have to link the issue to the Project, too.
